name: github-pages
on:
  push:
    branches:
      - main
jobs:
  github-pages:
    name: Publish to Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Run integration tests
        run: npm run deploy
